version: '3.1'
services:
  stats-server:
    build: ./explore-with-me-stat-app/
    image: dock_image_stats
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
    - SPRING_DATASOURCE_USERNAME=stat_app_user
    - SPRING_DATASOURCE_PASSWORD=stat_app_pass

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: stats-db
    ports:
      - "6590:5432"
    environment:
    - POSTGRES_DB=stats
    - POSTGRES_USER=stat_app_user
    - POSTGRES_PASSWORD=stat_app_pass

  ewm-service:
    build: ./explore-with-me-core-app/
    image: dock_image_ewm
    container_name: explore-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore
      - SPRING_DATASOURCE_USERNAME=explore_app_user
      - SPRING_DATASOURCE_PASSWORD=explore_app_pass
      - EXPLORE_STAT_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: explore-db
    ports:
      - "6580:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=explore_app_user
      - POSTGRES_PASSWORD=explore_app_pass